# Generated by Django 2.2.10 on 2020-03-08 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20200308_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(null=True, related_name='authors', to='demo.Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='number',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='demo.BookNumber'),
        ),
    ]
